config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :phones
  resources :services
  resources :addresses
  resources :drivers
  resources :vehicles
  resources :clients

  devise_for :users
  root 'welcome#index' 
  get '/:id', to: "welcome#index"

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :address
  belongs_to :driver
  belongs_to :client
  belongs_to :vehicle

  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true
  
  validates :status, :price, :data, presence: true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.00} 
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  
  # GET /services/new
  def new
    @service = Service.new
    drivers_for_select
    clients_for_select
    vehicles_for_select
    @service.build_address

  end

  # GET /services/1/edit
  def edit
    drivers_for_select
    clients_for_select
    vehicles_for_select
  end


  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    drivers_for_select
    clients_for_select
    vehicles_for_select

    respond_to do |format|
      
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        @service.build_address
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def drivers_for_select
    @driver_drivers_for_select = Driver.all
  end

  def clients_for_select
    @client_clients_for_select = Client.all
  end

  def vehicles_for_select
    @vehicle_vehicles_for_select = Vehicle.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.where("id = ?", params[:id]).first
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:status, :price, :data, :address_id, :driver_id, :client_id, :vehicle_id, address_attributes: [:street, :neighborhood, :zipcode, :number, :city])
    end

    def address_params
      params.require(:service).permit(:street, :neighborhood, :zipcode, :number, :city)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "row">

    <div class="form-group col-2">
      <%= form.label :status %>
      <%= form.select :status, ['On hold', 'Running','Concluded' ],{}, {class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]}%>
    </div>

    <div class="form-group col-2">
      <%= form.label :price %>
      <%= form.text_field :price, class: ["form-control", "form-control-user"] %>
    </div>

    <div class="form-group col-2">
      <%= form.label "Date" %>
      <%= form.datetime_local_field :data, class: ["form-control", "form-control-user"] %>
    </div>
  
    <%= form.fields_for :address do |address_fields| %>
      <div class="form-group col-6">
        <%= address_fields.label :street %>
        <%= address_fields.text_field :street, class: ["form-control", "form-control-user"] %>
      </div>

      <div class="form-group col-3">
        <%= address_fields.label :neighborhood %>
        <%= address_fields.text_field :neighborhood, class: ["form-control", "form-control-user"] %>
      </div>

      <div class="form-group col-3">
        <%= address_fields.label :zipcode %>
        <%= address_fields.text_field :zipcode, class: ["form-control", "form-control-user"] %>
      </div>

      <div class="form-group col-3">
        <%= address_fields.label :number %>
        <%= address_fields.text_field :number, class: ["form-control", "form-control-user"] %>
      </div>

      <div class="form-group col-3">
        <%= address_fields.label :city %>
        <%= address_fields.text_field :city, class: ["form-control", "form-control-user"] %>
      </div>
    <%end%>
  </div>  

  <div class="row">  
    <div class="form-group col-4">
      <%= form.label :client_id %>
      <%= form.collection_select(:client_id, @client_clients_for_select, :id, :name,{:selected => @service.client_id},{class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]})%>
    </div>
  
    <div class="form-group col-4">
      <%= form.label :driver_id %>
      <%= form.collection_select(:driver_id, @driver_drivers_for_select, :id, :name, {:selected => @service.driver_id},{class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]})%>
    </div>

    <div class="form-group">
      <%= form.label :vehicle_id %>
      <%= form.collection_select(:vehicle_id, @vehicle_vehicles_for_select, :id, :board, {:selected => @service.vehicle_id},{class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]})%>
    </div>
  </div>

  <div class="actions form-group ml-3 float-right">
    <%= form.submit "Save", class: ["btn", "btn-primary", "btn-user", "btn-block"] %>
  </div>


<% end %>

app/views/services/edit.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">Editing Service</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                    <%= render 'form', service: @service %>
                    <%= link_to @service, class: ["btn", "btn-info", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Show</span>
                    <% end %>

                    <%= link_to services_path, class: ["btn", "btn-light", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Back</span>
                    <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>
</div>

app/views/services/index.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
        <div class = "row">
          <h1 class="h3 mb-0 text-gray-800 ml-3">Services</h1>
          <%= link_to new_service_path, class: ["btn", "btn-primary", "btn-icon-split", "ml-3"] do  %>
            <span class="text">New Services</span>
          <% end %>
        </div>

          <div class="card shadow mb-4 mt-4">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Status</th>
                      <th>Price</th>
                      <th>Date</th>
                      <th>Driver</th>
                      <th>Client</th>
                      <th>Vehicle</th>
                      <th>Address</th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Status</th>
                      <th>Price</th>
                      <th>Date</th>
                      <th>Driver</th>
                      <th>Client</th>
                      <th>Vehicle</th>
                      <th>Address</th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </tfoot>
                  <tbody>
                  <% @services.each do |service| %>
                    <tr>
                      <td><%= service.status %></td>
                      <td><%= service.price %></td>
                      <td><%= service.data %></td>
                      <td><%= service.driver.name %></td>
                      <td><%= service.client.name %></td>
                      <td><%= service.vehicle.board%></td>
                      <td><%= service.address.street + " - " + service.address.number + " - " + service.address.neighborhood + " - " + service.address.city%></td>
                      <td class="text-center"><%= link_to service, class: ["btn", "btn-info", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-info-circle"></i></span><span class="text">Show</span>
                        <% end %>
                      </td>
                      <td class="text-center"><%= link_to edit_service_path(service), id: "e-#{service.data}", class: ["btn", "btn-secondary", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-arrow-right"></i></span><span class="text">Edit</span>
                        <% end %>
                      </td>
                      <td class="text-center"><%= link_to service, method: :delete, data: { confirm: 'Are you sure?' } , class: ["btn", "btn-danger", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-trash"></i></span>
                        <span class="text">Destroy</span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <br>

      <div>

    <%= render partial: 'dashbord/footer' %>

  <div>
  <%= render partial: 'dashbord/logout' %>

</div>

app/views/services/new.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">New Service</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                    <%= render 'form', service: @service %>
                    <%= link_to services_path, class: ["btn", "btn-light", "btn-icon-split", "float-right"] do  %>
                        <span class="text">Back</span>
                    <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>

</div>

app/views/services/show.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">Show Client</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                  <p>
                    <strong>Status:</strong>
                    <%= @service.status %>
                  </p>

                  <p>
                    <strong>Price:</strong>
                    <%= @service.price %>
                  </p>

                  <p>
                    <strong>Date:</strong>
                    <%= @service.data %>
                  </p>

                  <p>
                    <strong>Address:</strong>
                    <%= @service.address.street + " - " + @service.address.number + " - " + @service.address.neighborhood + " - " + @service.address.city %>
                  </p>

                  <p>
                    <strong>Driver:</strong>
                    <%= @service.driver.name %>
                  </p>

                  <p>
                    <strong>Client:</strong>
                    <%= @service.client.name %>
                  </p>

                  <p>
                    <strong>Vehicle:</strong>
                    <%= @service.vehicle.board %>
                  </p>

                  <%= link_to edit_service_path(@service), class: ["btn", "btn-secondary", "btn-icon-split", "float-right", "ml-3"] do  %>
                      <span class="text">Edit</span>
                  <% end %>

                  <%= link_to services_path, class: ["btn", "btn-light", "btn-icon-split", "float-right", "ml-3"] do  %>
                      <span class="text">Back</span>
                  <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>
</div>