config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :phones
  resources :services
  resources :addresses
  resources :drivers
  resources :vehicles
  resources :clients

  devise_for :users
  root 'welcome#index' 
  get '/:id', to: "welcome#index"

end

app/views/dashbord/_dashbord.html.erb
<!-- Sidebar -->

<div>
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion h-100" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/home/index">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">JM GUINDASTES</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <%= link_to "/home/index", class: ["nav-link"] do  %>
      <i class="fas fa-fw fa-home"></i>
          <span>Dashbord</span>
      <% end %>  
    </li>

    <!-- Heading -->
    <div class="sidebar-heading">Menu</div>

    <!-- Nav Item - Pages Collapse Menu -->
    <hr class="sidebar-divider">
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-fw fa-user"></i>
        <span>Clients</span>
      </a>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Clients Menu</h6>
            <%= link_to "New Client", new_client_path, class: ["collapse-item"] %>
            <%= link_to "List Clients", clients_path, class: ["collapse-item"] %>
        </div>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
        <i class="fas fa-fw fa-road"></i>
        <span>Drivers</span>
      </a>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Drivers Menu</h6>
            <%= link_to "New Driver", new_driver_path, class: ["collapse-item"] %>
            <%= link_to "List Drivres", drivers_path, class: ["collapse-item"] %>
        </div>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
        <i class="fas fa-fw fa-suitcase"></i>
        <span>Services</span>
      </a>
      <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Services Menu</h6>
            <%= link_to "New Service", new_service_path, class: ["collapse-item"] %>
            <%= link_to "List Services", services_path, class: ["collapse-item"] %>
        </div>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
        <i class="fas fa-fw fa-car"></i>
        <span>Vehicle</span>
      </a>
      <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Vehicles Menu</h6>
            <%= link_to "New Vehicle", new_vehicle_path, class: ["collapse-item"] %>
            <%= link_to "List Vehicle", vehicles_path, class: ["collapse-item"] %>
        </div>
      </div>
    </li>
    <!-- Divider -->

  </ul>
</div>
<!-- End of Sidebar -->

app/views/dashbord/_footer.html.erb
<footer class="sticky-footer bg-white footer navbar-fixed-boottom">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

app/views/dashbord/_loginTopbar.html.erb
<div>
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <div class="ml-3">
            <span>JM GUINDASTES </span>
            <i class="fa fa-truck ml-2"></i>
        </div>

        <div class = "col-5">
            <p id="notice"><%= notice %></p>
            <p><%= @notice %></p>
        </div>

        
        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>
        
        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <li class="mr-3">
                 <div class = "row">
                    <%= link_to "users/sign_up", class: ["btn", "btn-primary", "btn-icon-split", "ml-3"] do  %>
                        <span class="text">Register</span>
                    <% end %>
                </div>
            </li>
            <div class="topbar-divider d-none d-sm-block"></div>
            <li class="mr-3">
                 <div class = "row">
                    <%= link_to "users/sign_in", class: ["btn", "btn-primary", "btn-icon-split", "ml-3"] do  %>
                        <span class="text">Log In</span>
                    <% end %>
                </div>
            </li>
        </ul>
    </nav>
</div>

app/views/dashbord/_logout.html.erb
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: ["btn", "btn-primary"]%>
        </div>
        </div>
    </div>
</div>

app/views/dashbord/_topbar.html.erb
<div>
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <div class = "col-5">
            <p id="notice"><%= notice %></p>
        </div>
        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
        </button>
        
        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
        
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-users"></i>
                <span class="mr-2 ml-2 d-none d-lg-inline text-gray-600 small">USER</span>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
            </div>
        </li>

        </ul>

    </nav>

</div>