config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :phones
  resources :services
  resources :addresses
  resources :drivers
  resources :vehicles
  resources :clients

  devise_for :users
  root 'welcome#index' 
  get '/:id', to: "welcome#index"

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	has_one :service, dependent: :destroy

	validates_uniqueness_of :board
	validates :status, :board, :category, presence:true
	validates_length_of :board, maximum: 7
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:category, :board, :status)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

     <div class="form-group col-4">
      <%= form.label :category %>
      <%= form.select :category, ['Truck', 'Articulated crane','Hydraulic crane', 'Flatbed trailer', 'Normal trailer'],{}, {class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]}%>
    </div>

    <div class="form-group col-4">
      <%= form.label :board %>
      <%= form.text_field :board, class: ["form-control", "form-control-user"] %>
    </div>

     <div class="form-group col-4">
      <%= form.label :status %>
      <%= form.select :status, ['Available', 'Unavailable'],{}, {class: ["custom-select", "custom-select-sm", "form-control", "form-control-sm"]}%>
    </div>
  </div>

  <div class="actions form-group ml-3 float-right">
    <%= form.submit "Save", class: ["btn", "btn-primary", "btn-user", "btn-block"] %>
  </div>
  
<% end %>

app/views/vehicles/edit.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">Editing Vehicle</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                    <%= render 'form', vehicle: @vehicle %>
                    <%= link_to @vehicle, class: ["btn", "btn-info", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Show</span>
                    <% end %>

                    <%= link_to vehicles_path, class: ["btn", "btn-light", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Back</span>
                    <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>
</div>

app/views/vehicles/index.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
        <div class = "row">
          <h1 class="h3 mb-0 text-gray-800 ml-3">Vehicle</h1>
          <%= link_to new_vehicle_path, class: ["btn", "btn-primary", "btn-icon-split", "ml-3"] do  %>
            <span class="text">New Vehicle</span>
          <% end %>
        </div>

          <div class="card shadow mb-4 mt-4">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Category</th>
                      <th>Board</th>
                      <th>Status</th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Category</th>
                      <th>Board</th>
                      <th>Status</th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </tfoot>
                  <tbody>
                  <% @vehicles.each do |vehicle| %>
                    <tr>
                      <td><%= vehicle.category %></td>
                      <td><%= vehicle.board %></td>
                      <td><%= vehicle.status %></td>
                      <td class="text-center"><%= link_to vehicle, id: "s-#{vehicle.board}", class: ["btn", "btn-info", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-info-circle"></i></span><span class="text">Show</span>
                        <% end %>
                      </td>
                      <td class="text-center"><%= link_to edit_vehicle_path(vehicle), id: "e-#{vehicle.board}", class: ["btn", "btn-secondary", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-arrow-right"></i></span><span class="text">Edit</span>
                        <% end %>
                      </td>
                      <td class="text-center"><%= link_to vehicle, id: "d-#{vehicle.board}", method: :delete, data: { confirm: 'Are you sure?' } , class: ["btn", "btn-danger", "btn-icon-split"] do  %>
                        <span class = "icon text-white-30"><i class="fas fa-trash"></i></span>
                        <span class="text">Destroy</span>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <br>

      <div>

    <%= render partial: 'dashbord/footer' %>

  <div>
  <%= render partial: 'dashbord/logout' %>

</div>

app/views/vehicles/new.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">New Vehicle</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                    <%= render 'form', vehicle: @vehicle %>
                    <%= link_to vehicles_path, class: ["btn", "btn-light", "btn-icon-split", "float-right"] do  %>
                        <span class="text">Back</span>
                    <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>

</div>

app/views/vehicles/show.html.erb
<div id="wrapper">
  <%= render partial: 'dashbord/dashbord' %>

  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
    <div id="content">
        <%= render partial: 'dashbord/topbar' %>

        <div class="container-fluid">
            <div class = "row">
                <h1 class="h3 mb-0 text-gray-800 ml-3">Show Vehicle</h1>
            </div>

            <div class="card shadow mb-4 mt-4">
                <div class="card-body">
                    <p>
                      <strong>Category:</strong>
                      <%= @vehicle.category %>
                    </p>

                    <p>
                      <strong>Board:</strong>
                      <%= @vehicle.board %>
                    </p>

                    <p>
                      <strong>Status:</strong>
                      <%= @vehicle.status %>
                    </p>
                    <%= link_to edit_vehicle_path(@vehicle), class: ["btn", "btn-secondary", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Edit</span>
                    <% end %>

                    <%= link_to vehicles_path, class: ["btn", "btn-light", "btn-icon-split", "float-right", "ml-3"] do  %>
                        <span class="text">Back</span>
                    <% end %>
                </div>
             </div>
        </div>
        <br>
      <div>
    <%= render partial: 'dashbord/footer' %>
  <div>
  <%= render partial: 'dashbord/logout' %>
</div>